sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

arch:
  - amd64
  - arm64-graviton2

virt: lxd
group: edge

jdk:
  - openjdk11

script:
  - sudo update-alternatives --config java
  - sudo update-alternatives --config javac
  - sbt scriptit
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
